apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodeapp
          image: 176768607918.dkr.ecr.ap-south-1.amazonaws.com/github-nodejs:nodeapp
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
